### PR TITLE
save latest selections in cookies

### LINKED ISSUE #36: Latest event, property, aggregation, and time range should be saved
Currently, you need to select the event, property, aggregation and time range again when closing the tab and going back to the project.

It would improve the UX if we save the last picked value for those on a per project basis in a cookie.

### PR DESCRIPTION
**Pull request by Buesi**
- saves latest selections to cookies
- saved selection is used if no other params are chosen
- if neither cookies nor params are available, selection goes back to default
- closes #36

### CODE REVIEW

**Comment by Buesi** [comment]
should I also write some tests?

**Comment by shafy** [comment]
> should I also write some tests?

Yes please :-)

**Comment by Buesi** [comment]
What should I do with the failed checks?

**Comment by Buesi** [comment]
for the gem nokogiri there has been a new version (22.Feb 22) [1.13.3](https://rubygems.org/gems/nokogiri/versions/1.13.3), should I update it in the code to 1.13.3?

**Comment by shafy** [comment]
> for the gem nokogiri there has been a new version (22.Feb 22) [1.13.3](https://rubygems.org/gems/nokogiri/versions/1.13.3), should I update it in the code to 1.13.3?

Yes, exactly. You can see what needs to be done if you click on "Details" or if you run `brakeman` and `bundle-audit --update` in your environment (the automated GitHub check basically does that under the hood).

But I'll update it now, no worries.

**Pull request merged**
